### ISSUE TITLE
Configuration of addresses could be more robust

### ISSUE THREAD

**Issue by jaresty** [cloudfoundry-incubator/routing-acceptance-tests#5]
We need to configure the TCP router IP address in order to run RATs.  Unfortunately, the router IP address varies by deployment and also may be unstable if you are tearing down and recreating an environment.  This forces us to manually update the IP address for each environment and also each time we recreate an environment.  

If instead, RATs accepted a DNS name (e.g. tcp.luna.cf-app.com) for the tcp router address, then we wouldn't need to change it every time we recreate an environment.  This would be a bit better for our use case, and it's not clear to us why it wouldn't work.

cc: @staylor

**Comment by shashwathi** [comment]
@jaresty @staylor : 

RATs does accept a DNS name (e.g. tcp.luna.cf-app.com) for the tcp router address. We are currently running RATS in our CI environments with DNS name and we haven't had any issues. 

Closing this issue for now. Feel free to open another issue if you are having trouble running RATS.

Regards
Shash

**Comment by jaresty** [comment]
Hi @shashwathi,

Thanks for letting us know!  Perhaps you could update [the example
config.json on this page](
https://github.com/cloudfoundry-incubator/routing-acceptance-tests/blob/c11cc87f540a20eac2003203976ba04470a3b41f/README.md)
to use a DNS name instead of an IP address?  Since the api key on that page
contains api.bosh-lite.com while the "addresses" section is using an IP
address, it appears as if the proper configuration requires an IP address.

Thanks,
Josh && @staylor

**Comment by aaronshurley** [comment]
@jaresty: 

I agree we need to add more documentation for `addresses` property in config.json. We have just updated the [README](https://github.com/cloudfoundry-incubator/routing-acceptance-tests/commit/b3b4839354117167ecee9423cfa6bc11e1c4788a), please let us know if it's still unclear.

Regards
Aaron & @shashwathi

**Comment by jaresty** [comment]
Thanks - it looks much better now!
2017年1月23日(月) 10:14 Aaron Hurley <notifications@github.com>:
